//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreelancersOfAProject
    {
        public string ProjectTitle { get; set; }
        public string FreelancerName { get; set; }
        public string Email { get; set; }
    }
}
