//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsPostedByEmployer
    {
        public string EmployerName { get; set; }
        public string Title { get; set; }
        public int Minimum_Payment { get; set; }
        public int Maximum_Payment { get; set; }
        public string Job_Category { get; set; }
    }
}
