//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Text { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public int JobId { get; set; }
        public int EmployerId { get; set; }
        public int FreelancerId { get; set; }
    
        public virtual Attachment Attachment { get; set; }
    }
}
